version: "3"
services:
    api:
        build: .
        depends_on:
          - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro #./ means current directory, can also write ./app if want only app directory to copy to docker.ro means read only so that docker cannot change anything in our local file.
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env #refer to environment variables present in our currect directory.Either use this or below with actual name of all variables.
        environment:
          - DATABASE_URL=postgresql://postgres:Jine1921@postgres:5432/fastapi
          - SECRET_KEY=7f4f3d0c9d5e1a8b6f2c4d9e7a1b3c5d8e0f2a4b6c8d1e3f5a7b9c0d2e4f6a8
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=60
    postgres:
      image: postgres:16  #creating db with already created image file
      environment: #need to set some variables
          - POSTGRES_PASSWORD=Jine1921
          - POSTGRES_DB=fastapi

      volumes: #this is used to store all our data at the given location if our container goes down
          - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: