name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_URL=postgresql://jinendra.soni:Jine1921@127.0.0.1:5432/fastapi
      SECRET_KEY=7f4f3d0c9d5e1a8b6f2c4d9e7a1b3c5d8e0f2a4b6c8d1e3f5a7b9c0d2e4f6a8
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest